name: False Positive Report
description: Create a report to suggest a false positive.
title: "False Positive | example.com"
labels:
  - "false positive"
assignees:
  - funilrys
  - mitchellkrogza
  - spirillen
  - g0d33p3rsec
projects:
  - Phishing-Database/2
body:
  - type: markdown
    attributes:
      value: |+
        Thanks for taking the time to fill out this false positive report!

        We understand that this can be frustrating, confusing, embarrassing, time consuming, and even painful for many webmasters, developers, user and websites or services owners.
        Please be patient and rest assured that we one of our team members will address your issue as soon as possible. Please be sure to provide as much information as possible to help us understand the issue.

        All issues are welcome, but please be aware that:
          - We are a small team and may not be able to respond immediately.
          - We may ask for more information to help us understand the issue.
          - Your issue may be moved to one of our other repositories for further investigation.

        We appreciate your help in making the Phishing Database better!

        If you have a question or need help, please ask in our [Discussions](https://github.com/Phishing-Database/dev-center/discussions) section.

        The Phishing Database Project Team.

  - type: textarea
    id: target-subjects
    attributes:
      label: What are the subjects of the false-positive (domains, URLs, or IPs)?
      description: |
        Please list any domains, URLs or IPs that you believe are false-positives.

        Please warn with "NSFW" where applicable.
      placeholder: |
        * example.com
        * sub.example.com
        * https://example.com/page
        * https://sub.example.com/page
        * **NSFW** example.com
        * 192.168.0.0/16
      value: |
        * example.com
        * sub.example.com
        * https://example.com/page
        * https://sub.example.com/page
        * **NSFW** example.com
        * 192.168.0.0/16
    validations:
      required: true
  - type: textarea
    id: false-positive
    attributes:
      label: Why do you believe this is a false-positive?
      description: Please explain why you believe this is a false-positive.
      placeholder: |
        I believe this is a false-positive because...
      value: |
        I believe this is a false-positive because...
    validations:
      required: true
  - type: dropdown
    id: discovery
    attributes:
      label: How did you discover this false-positive(s)?
      description: Please provide any information that may help us understand how you discovered this false-positive(s).
      multiple: true
      options:
        - VirusTotal
        - Phishtank
        - OpenPhish
        - Website was hacked
        - Other (Please fill out the next box)
    validations:
      required: true

  - type: textarea
    id: discovery-other
    attributes:
      label: Where did you find this false-positive if not listed above?
      description: Please provide any information that may help us understand how you discovered this false-positive(s).
      placeholder: |
        I discovered this false-positive by...
      value: |
        I discovered this false-positive by...
    validations:
      required: true

  - type: textarea
    id: peer-sources-review
    attributes:
      label: Have you requested a review from other sources?
      description: |
        Please include any relevant links to your existing removal or whitelisting requests.
      placeholder: |
        I have requested a review from...
      value: |
        I have requested a review from...
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Do you have a screenshot?
      description: |
        If applicable to the problem, please provide some screenshots to help explain the problem.

        Please note that there need to be at least one blank line separating before and after the image line.
        To add an image, use the following code: `![Screenshot of False Positive](https://example.com/path/to/image.png)`
      placeholder: |
        <details><summary>Screenshot</summary>


        </details>
      value: |
        <details><summary>Screenshot</summary>
        </details>
    validations:
      required: false
  - type: textarea
    id: more-info
    attributes:
      label: Additional Information or Context
      description: Is there anything else you'd like to add?
      placeholder: |
        I have also noticed that...
      value: |
        I have also noticed that...
    validations:
      required: false

